AWSTemplateFormatVersion: 2010-09-09
Parameters: 
  Env: 
    Type: String
    #Default: dev
    AllowedValues: 
      - manage
      - dev
      - prod
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub megun-terraform-samples-tfstate-${Env}
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: env
          Value: !Ref Env
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub megun-terraform-samples-tflock-${Env}
      AttributeDefinitions:
      - AttributeName: "LockID"
        AttributeType: "S"
      BillingMode: "PAY_PER_REQUEST"
      KeySchema:
      - AttributeName: "LockID"
        KeyType: "HASH"
      Tags:
        - Key: env
          Value: !Ref Env
Outputs:
  BucketNameTfstate:
    Value: !Ref S3Bucket
  TableNameTflock:
    Value: !Ref DynamoDBTable
